name: Deploy React App
on: [push]
jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: test_app
    steps:
      - name: Get the repo code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get the repo code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Build Applicaton
        run: npm run build
      - name: Deploy
        run: echo Deploy-project
