name: Test React App
on: [push]
jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        # run:
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run test
